server:
  port: 0

spring:
  kafka:
    bootstrap-servers: infra.internal:9092

  datasource:
    url: jdbc:mysql://rdb.internal:3306/notifyme
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka.internal:8761/eureka/
  instance:
    prefer-ip-address: true