notification:
  scheduler:
    id: 1
    lock-until-minutes: 5
  channels:
    EMAIL:
      topic-request: notification.email.send-request
      topic-result: notification.common.send-result
    SLACK:
      topic-request: notification.slack.send-request
      topic-result: notification.common.send-result

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
  datasource:
    url: jdbc:mysql://localhost:3307/notifyme
    username: root
    password: gksrud12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false