spring:
  profiles:
    active: local

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-api
              uri: lb://notification-auth
              predicates:
                - Path=/api/v1/auth/**
            - id: notification-api
              uri: lb://notification-api
              predicates:
                - Path=/api/v1/notifications/**

auth:
  jwt:
    secret: xbvbTGBf9G9jt76SMnx3s3fCAY5EHaCD
  whitelist:
    paths:
      - /api/v1/auth/**