server:
  port: 0

spring:
  r2dbc:
    url: r2dbc:pool:mysql://rdb.internal:3306/notifyme
  data:
    redis:
      host: infra.internal
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka.internal:8761/eureka/ # Eureka 서버 주소
  instance:
    prefer-ip-address: true # 호스트 이름보다 IP 주소를 우선 사용 (권장)